/**
 * API Route: Create Invoice PDF
 * Generates a PDF invoice
 * 
 * STRIPE INTEGRATION:
 * To integrate with Stripe:
 * 1. Add STRIPE_SECRET_KEY to .env
 * 2. Use Stripe API to create invoice: stripe.invoices.create()
 * 3. Return Stripe invoice PDF URL or generate custom PDF
 */
import { NextRequest, NextResponse } from 'next/server';
import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

export async function POST(request: NextRequest) {
  try {
    const data = await request.json();
    
    // Save invoice to JSON
    const invoicesPath = path.join(process.cwd(), 'data', 'invoices.json');
    let invoices = [];
    if (fs.existsSync(invoicesPath)) {
      invoices = JSON.parse(fs.readFileSync(invoicesPath, 'utf8'));
    }
    
    const invoice = {
      id: `inv-${Date.now()}`,
      clientName: data.clientName,
      amount: parseFloat(data.amount),
      status: 'draft',
      dueDate: data.dueDate,
      createdAt: new Date().toISOString()
    };
    
    invoices.push(invoice);
    fs.writeFileSync(invoicesPath, JSON.stringify(invoices, null, 2));

    // Generate PDF
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];
    
    doc.on('data', (chunk) => chunks.push(chunk));
    
    doc.fontSize(24).text('INVOICE', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`Client: ${data.clientName}`, { align: 'left' });
    doc.text(`Amount: $${data.amount}`, { align: 'left' });
    doc.text(`Due Date: ${new Date(data.dueDate).toLocaleDateString()}`, { align: 'left' });
    doc.text(`Invoice #: ${invoice.id}`, { align: 'left' });
    doc.moveDown();
    doc.text('Generated by Guerrilla Social Club', { align: 'center' });
    
    doc.end();
    
    await new Promise((resolve) => {
      doc.on('end', resolve);
    });
    
    const pdfBuffer = Buffer.concat(chunks);
    
    return new NextResponse(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="invoice-${invoice.id}.pdf"`
      }
    });
  } catch (error) {
    console.error('Error creating invoice:', error);
    return NextResponse.json(
      { error: 'Failed to create invoice' },
      { status: 500 }
    );
  }
}

